version: 2

models:
  - name: dim_customers
    description: "Information of customers"
    columns:
      - name: customer_id
        description: "First name of the customers"
        tests:
          - unique
          - not_null
      - name: first_name
        description: "First name of the customers"
        tests:
          - not_null
      - name: last_name
        description: "Last name of the customers"
        tests:
          - not_null
      - name: gender
        description: "Gender of the customers"
        tests:
          - not_null

  - name: dim_location
    description: "Information of location"
    columns:
      - name: city_id
        tests:
          - unique
          - not_null
      - name: city_names
        description: "Name of the city"
        tests:
          - not_null
      - name: province_id
        tests:
          - not_null
      - name: province_names
        tests:
          - not_null

  - name: dim_products
    description: "Information of products"
    columns:
      - name: product_id
        tests:
          - unique
          - not_null
      - name: product_name
        description: "Name of the product"
        tests:
          - not_null
      - name: size
        description: "Size of the product"
        tests:
          - not_null
      - name: price
        description: "Price of the product"
        tests:
          - not_null
      - name: product_category_id
        tests:
          - unique
          - not_null
      - name: product_category_name
        description: "Product category name of the product"
        tests:
          - not_null